spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # Especifica el dialecto
      hibernate.default_schema: practica  # Especifica el esquema
    hibernate:
      ddl-auto: update  # Opciones: none, update, create, create-drop
    show-sql: true  # Muestra las consultas SQL en la consola
